"""empty message

Revision ID: 2fa25dacc653
Revises: 
Create Date: 2018-03-14 19:22:32.587702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa25dacc653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_foodtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.String(length=32), nullable=True),
    sa.Column('typename', sa.String(length=100), nullable=True),
    sa.Column('childtypenames', sa.String(length=200), nullable=True),
    sa.Column('typesort', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.String(length=32), nullable=True),
    sa.Column('productimg', sa.String(length=200), nullable=True),
    sa.Column('productname', sa.String(length=100), nullable=True),
    sa.Column('productlongname', sa.String(length=200), nullable=True),
    sa.Column('isxf', sa.Boolean(), nullable=True),
    sa.Column('pmdesc', sa.String(length=100), nullable=True),
    sa.Column('specifics', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('marketprice', sa.String(length=100), nullable=True),
    sa.Column('categoryid', sa.String(length=32), nullable=True),
    sa.Column('childcid', sa.String(length=32), nullable=True),
    sa.Column('childcidname', sa.String(length=100), nullable=True),
    sa.Column('dealerid', sa.String(length=32), nullable=True),
    sa.Column('storenums', sa.String(length=32), nullable=True),
    sa.Column('productnum', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_mainshow',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('trackid', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.String(length=32), nullable=True),
    sa.Column('brandname', sa.String(length=100), nullable=True),
    sa.Column('img1', sa.String(length=200), nullable=True),
    sa.Column('childcid1', sa.String(length=32), nullable=True),
    sa.Column('productid1', sa.String(length=32), nullable=True),
    sa.Column('longname1', sa.String(length=200), nullable=True),
    sa.Column('price1', sa.String(length=100), nullable=True),
    sa.Column('marketprice1', sa.String(length=100), nullable=True),
    sa.Column('img2', sa.String(length=200), nullable=True),
    sa.Column('childcid2', sa.String(length=32), nullable=True),
    sa.Column('productid2', sa.String(length=32), nullable=True),
    sa.Column('longname2', sa.String(length=200), nullable=True),
    sa.Column('price2', sa.String(length=100), nullable=True),
    sa.Column('marketprice2', sa.String(length=100), nullable=True),
    sa.Column('img3', sa.String(length=200), nullable=True),
    sa.Column('childcid3', sa.String(length=32), nullable=True),
    sa.Column('productid3', sa.String(length=32), nullable=True),
    sa.Column('longname3', sa.String(length=200), nullable=True),
    sa.Column('price3', sa.String(length=32), nullable=True),
    sa.Column('marketprice3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_mustbuy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('trackid', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('trackid', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('trackid', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_wheel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('trackid', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_wheel')
    op.drop_table('axf_shop')
    op.drop_table('axf_nav')
    op.drop_table('axf_mustbuy')
    op.drop_table('axf_mainshow')
    op.drop_table('axf_goods')
    op.drop_table('axf_foodtypes')
    # ### end Alembic commands ###
